before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-lxml python-openssl

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - /usr/bin/yes | env PYTHONPATH=. coverage run --source=lisa `which trial` lisa.server

after_success:
  - coveralls

services:
  - mongodb

notifications:
  irc: "irc.freenode.net#lisa-project"
  
branches:
  only:
    - master
